name: "fastapi_revised"
services:
  fastapi_api:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_revised_container_2
    ports:
      - "4000:8000" # - "host_machine_port:container_port" -> Bind(map) container_port(8000) to host machine port(4000)